//! Typed emitter — Service IR → tatara-lisp source.
//!
//! Per ★★ TYPED EMISSION, every form goes through `lava_forge::SExpr`
//! + the canonical pretty-printer. No format!() of tatara-lisp.

use crate::spec::{AwsMetadata, Method, Operation, Service, Shape, ShapeKind, ShapeMember};
use lava_forge::{render, SExpr};

/// Render a Service to a complete tatara-lisp source file.
///
/// Layout:
///
/// ```lisp
/// ;; <service>-api.tlisp — auto-generated by lava-api-forge
///
/// (defapi-service :ec2
///   :version "2016-11-15"
///   :protocol ec2Query
///   :auth sigv4
///   :auth-source "v4"
///   :endpoint-prefix "ec2"
///   :doc "...")
///
/// (defapi-shape :create-vpc-request
///   :kind object
///   :required (:cidr-block)
///   :members ((:cidr-block :shape :string :doc "...")
///             (:instance-tenancy :shape :tenancy :doc "...")))
///
/// (defapi-shape :tenancy :kind enum :values ("default" "dedicated" "host"))
///
/// (defapi-operation :ec2/create-vpc
///   :method post
///   :path "/"
///   :input :create-vpc-request
///   :output :create-vpc-result
///   :doc "Creates a VPC with the specified IPv4 CIDR block.")
/// ```
#[must_use]
pub fn render_service(svc: &Service) -> String {
    let mut out = String::new();
    out.push_str(";; ");
    out.push_str(&svc.name);
    out.push_str("-api.tlisp — auto-generated by lava-api-forge.\n");
    out.push_str(";; Do NOT edit; re-run lava-api-forge against the upstream API spec.\n\n");

    // (defapi-service :name :version "x" :protocol … :auth … :doc "...")
    let mut svc_form = vec![
        SExpr::sym("defapi-service"),
        SExpr::Kw(kw_body(&svc.name)),
        SExpr::Kw("version".to_string()),
        SExpr::Str(svc.version.clone()),
    ];
    if let Some(aws) = &svc.aws {
        push_aws_metadata(&mut svc_form, aws);
    }
    if let Some(d) = &svc.doc {
        svc_form.push(SExpr::Kw("doc".to_string()));
        svc_form.push(SExpr::Str(d.clone()));
    }
    out.push_str(&render(&SExpr::List(svc_form)));
    out.push_str("\n\n");

    // Shapes (alphabetized for deterministic output).
    let mut shape_names: Vec<&String> = svc.shapes.keys().collect();
    shape_names.sort();
    for name in shape_names {
        let shape = svc.shapes.get(name).expect("present");
        out.push_str(&render(&render_shape(name, shape)));
        out.push_str("\n\n");
    }

    // Operations (alphabetized).
    let mut op_names: Vec<&String> = svc.operations.keys().collect();
    op_names.sort();
    for name in op_names {
        let op = svc.operations.get(name).expect("present");
        out.push_str(&render(&render_operation(&svc.name, op)));
        out.push_str("\n\n");
    }
    out
}

/// Append the AWS wire + auth keys to a `defapi-service` form.
///
/// `:protocol` and `:auth` carry Smithy's trait names; `:auth-source`
/// carries the botocore `signatureVersion` token they were translated
/// from, so the translation is always reversible. A scheme pleme-io has
/// no signer for emits `:auth unsupported`, which a generated client must
/// treat as a refusal rather than as "send it unsigned".
fn push_aws_metadata(form: &mut Vec<SExpr>, aws: &AwsMetadata) {
    form.push(SExpr::Kw("protocol".to_string()));
    form.push(SExpr::sym(aws.protocol.smithy_trait()));
    form.push(SExpr::Kw("auth".to_string()));
    form.push(SExpr::sym(aws.auth.smithy_scheme().unwrap_or("unsupported")));
    form.push(SExpr::Kw("auth-source".to_string()));
    form.push(SExpr::Str(aws.auth.botocore_token().to_string()));
    if !aws.endpoint_prefix.is_empty() {
        form.push(SExpr::Kw("endpoint-prefix".to_string()));
        form.push(SExpr::Str(aws.endpoint_prefix.clone()));
    }
    for (key, value) in [
        ("signing-name", &aws.signing_name),
        ("global-endpoint", &aws.global_endpoint),
        ("target-prefix", &aws.target_prefix),
        ("xml-namespace", &aws.xml_namespace),
    ] {
        if let Some(v) = value {
            form.push(SExpr::Kw(key.to_string()));
            form.push(SExpr::Str(v.clone()));
        }
    }
}

fn render_shape(name: &str, shape: &Shape) -> SExpr {
    let mut items = vec![SExpr::sym("defapi-shape"), SExpr::Kw(kw_body(name))];
    items.push(SExpr::Kw("kind".to_string()));
    match &shape.kind {
        ShapeKind::Primitive(p) => {
            items.push(SExpr::sym("primitive"));
            items.push(SExpr::Kw("type".to_string()));
            items.push(SExpr::sym(p.clone()));
        }
        ShapeKind::Object { members, required } => {
            items.push(SExpr::sym("object"));
            if !required.is_empty() {
                items.push(SExpr::Kw("required".to_string()));
                items.push(SExpr::List(
                    required.iter().map(|r| SExpr::Kw(kw_body(r))).collect(),
                ));
            }
            items.push(SExpr::Kw("members".to_string()));
            items.push(SExpr::List(members.iter().map(|(k, v)| render_member(k, v)).collect()));
        }
        ShapeKind::List { item } => {
            items.push(SExpr::sym("list"));
            items.push(SExpr::Kw("item".to_string()));
            items.push(SExpr::Kw(kw_body(item)));
        }
        ShapeKind::Map { value } => {
            items.push(SExpr::sym("map"));
            items.push(SExpr::Kw("value".to_string()));
            items.push(SExpr::Kw(kw_body(value)));
        }
        ShapeKind::Enum { values } => {
            items.push(SExpr::sym("enum"));
            items.push(SExpr::Kw("values".to_string()));
            items.push(SExpr::List(values.iter().map(|v| SExpr::Str(v.clone())).collect()));
        }
    }
    if let Some(d) = &shape.doc {
        items.push(SExpr::Kw("doc".to_string()));
        items.push(SExpr::Str(d.clone()));
    }
    SExpr::List(items)
}

fn render_member(name: &str, m: &ShapeMember) -> SExpr {
    let mut items = vec![
        SExpr::Kw(kw_body(name)),
        SExpr::Kw("shape".to_string()),
        SExpr::Kw(kw_body(&m.shape)),
    ];
    if m.sensitive {
        items.push(SExpr::Kw("sensitive".to_string()));
        items.push(SExpr::Bool(true));
    }
    if let Some(d) = &m.doc {
        items.push(SExpr::Kw("doc".to_string()));
        items.push(SExpr::Str(d.clone()));
    }
    SExpr::List(items)
}

fn render_operation(service_name: &str, op: &Operation) -> SExpr {
    let mut qualified = kw_body(service_name);
    qualified.push('/');
    qualified.push_str(&kw_body(&op.name));
    let mut items = vec![
        SExpr::sym("defapi-operation"),
        SExpr::Kw(qualified),
        SExpr::Kw("method".to_string()),
        SExpr::sym(method_sym(op.method)),
        SExpr::Kw("path".to_string()),
        SExpr::Str(op.path.clone()),
    ];
    if let Some(s) = &op.input_shape {
        items.push(SExpr::Kw("input".to_string()));
        items.push(SExpr::Kw(kw_body(s)));
    }
    if let Some(s) = &op.output_shape {
        items.push(SExpr::Kw("output".to_string()));
        items.push(SExpr::Kw(kw_body(s)));
    }
    if let Some(w) = &op.result_wrapper {
        // The XML element the real result is nested inside under the
        // query protocols. Emitted verbatim as a string: it is an
        // on-the-wire element name, not an identifier we own.
        items.push(SExpr::Kw("result-wrapper".to_string()));
        items.push(SExpr::Str(w.clone()));
    }
    if !op.errors.is_empty() {
        items.push(SExpr::Kw("errors".to_string()));
        items.push(SExpr::List(op.errors.iter().map(|e| SExpr::Kw(kw_body(e))).collect()));
    }
    if let Some(a) = op.auth_override {
        // Overrides the service-level :auth for this operation only.
        items.push(SExpr::Kw("auth".to_string()));
        items.push(SExpr::sym(a.smithy_scheme()));
        items.push(SExpr::Kw("auth-source".to_string()));
        items.push(SExpr::Str(a.botocore_token().to_string()));
    }
    if let Some(d) = &op.doc {
        items.push(SExpr::Kw("doc".to_string()));
        items.push(SExpr::Str(d.clone()));
    }
    SExpr::List(items)
}

/// CamelCase / PascalCase / snake_case → kebab-case keyword body.
/// `CreateVpcRequest` → `create-vpc-request`.
fn kw_body(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut prev_lower = false;
    for c in s.chars() {
        if c.is_uppercase() {
            if prev_lower {
                out.push('-');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
            prev_lower = false;
        } else if c == '_' {
            out.push('-');
            prev_lower = false;
        } else {
            out.push(c);
            prev_lower = c.is_alphanumeric();
        }
    }
    out
}

fn method_sym(m: Method) -> &'static str {
    match m {
        Method::Get => "get",
        Method::Post => "post",
        Method::Put => "put",
        Method::Patch => "patch",
        Method::Delete => "delete",
        Method::Head => "head",
        Method::Options => "options",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Collapse whitespace runs so assertions describe *content*, not the
    /// pretty-printer's line breaking (lava-forge puts every atom of an
    /// over-80-column form on its own line).
    fn flat(s: &str) -> String {
        s.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    #[test]
    fn kw_body_camel_to_kebab() {
        assert_eq!(kw_body("CreateVpcRequest"), "create-vpc-request");
        // Consecutive caps stay glued (no dash between adjacent uppers);
        // the rule is "insert dash on lower→upper transition".
        assert_eq!(kw_body("EC2"), "ec2");
        assert_eq!(kw_body("snake_case"), "snake-case");
        assert_eq!(kw_body("simple"), "simple");
    }

    #[test]
    fn renders_service_with_one_operation_and_one_shape() {
        let json = r#"{
          "metadata": {
            "serviceId": "EC2",
            "apiVersion": "2016-11-15",
            "endpointPrefix": "ec2",
            "protocol": "ec2",
            "signatureVersion": "v4"
          },
          "shapes": {
            "String": { "type": "string" },
            "CreateVpcRequest": {
              "type": "structure",
              "required": ["CidrBlock"],
              "members": { "CidrBlock": { "shape": "String" } }
            }
          },
          "operations": {
            "CreateVpc": {
              "http": { "method": "POST", "requestUri": "/" },
              "input": { "shape": "CreateVpcRequest" }
            }
          }
        }"#;
        let svc = crate::spec::from_botocore(json).unwrap();
        let out = render_service(&svc);
        assert!(out.contains("defapi-service"));
        assert!(out.contains(":ec2"));
        assert!(out.contains("defapi-operation"));
        assert!(out.contains(":ec2/create-vpc"));
        assert!(out.contains(":method"));
        assert!(out.contains("post"));
        assert!(out.contains("defapi-shape"));
        assert!(out.contains(":create-vpc-request"));
        assert!(out.contains(":cidr-block"));
        assert!(out.contains(":required"));
        // The wire facts now ride along on the service form.
        let flat = flat(&out);
        assert!(flat.contains(":protocol ec2Query"));
        assert!(flat.contains(":auth sigv4"));
    }

    #[test]
    fn unsignable_scheme_emits_unsupported_never_a_silent_sigv4() {
        // botocore `v2` has no Smithy trait and no pleme-io signer. The
        // emission must say so rather than round it up to sigv4, which
        // would produce a client that signs wrongly and fails at AWS.
        let json = r#"{
          "metadata": { "serviceId": "Legacy", "protocol": "query",
                        "signatureVersion": "v2", "endpointPrefix": "legacy" },
          "operations": {}
        }"#;
        let out = flat(&render_service(&crate::spec::from_botocore(json).unwrap()));
        assert!(out.contains(":auth unsupported"), "got:\n{out}");
        assert!(out.contains(":auth-source \"v2\""));
        assert!(!out.contains("sigv4"), "must not claim sigv4");
    }

    #[test]
    fn operation_errors_and_auth_override_are_emitted() {
        let json = r#"{
          "metadata": { "serviceId": "Demo", "protocol": "json",
                        "jsonVersion": "1.1", "signatureVersion": "v4",
                        "endpointPrefix": "demo", "targetPrefix": "DemoService" },
          "shapes": { "Req": { "type": "structure", "members": {} } },
          "operations": {
            "Ping": {
              "input": { "shape": "Req" },
              "errors": [ { "shape": "ThrottlingException" } ],
              "authtype": "none"
            }
          }
        }"#;
        let out = flat(&render_service(&crate::spec::from_botocore(json).unwrap()));
        assert!(out.contains(":protocol awsJson1_1"));
        assert!(out.contains(":target-prefix \"DemoService\""));
        assert!(out.contains(":errors (:throttling-exception)"), "got:\n{out}");
        // Operation-level auth overrides the service-level sigv4.
        assert!(out.contains(":auth noAuth"));
        assert!(out.contains(":auth-source \"none\""));
    }
}
